service: slack-zoom-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  memorySize: 256
  timeout: 30
  environment:
    NODE_OPTIONS: --enable-source-maps
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    ZOOM_ACCOUNT_A_ID: ${env:ZOOM_ACCOUNT_A_ID}
    ZOOM_ACCOUNT_A_ACCOUNT_ID: ${env:ZOOM_ACCOUNT_A_ACCOUNT_ID}
    ZOOM_ACCOUNT_A_CLIENT_ID: ${env:ZOOM_ACCOUNT_A_CLIENT_ID}
    ZOOM_ACCOUNT_A_CLIENT_SECRET: ${env:ZOOM_ACCOUNT_A_CLIENT_SECRET}
    ZOOM_ACCOUNT_B_ID: ${env:ZOOM_ACCOUNT_B_ID}
    ZOOM_ACCOUNT_B_ACCOUNT_ID: ${env:ZOOM_ACCOUNT_B_ACCOUNT_ID}
    ZOOM_ACCOUNT_B_CLIENT_ID: ${env:ZOOM_ACCOUNT_B_CLIENT_ID}
    ZOOM_ACCOUNT_B_CLIENT_SECRET: ${env:ZOOM_ACCOUNT_B_CLIENT_SECRET}
    ZOOM_ACCOUNT_C_ID: ${env:ZOOM_ACCOUNT_C_ID}
    ZOOM_ACCOUNT_C_ACCOUNT_ID: ${env:ZOOM_ACCOUNT_C_ACCOUNT_ID}
    ZOOM_ACCOUNT_C_CLIENT_ID: ${env:ZOOM_ACCOUNT_C_CLIENT_ID}
    ZOOM_ACCOUNT_C_CLIENT_SECRET: ${env:ZOOM_ACCOUNT_C_CLIENT_SECRET}

functions:
  slack:
    handler: src/index.handler
    url: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node20
    platform: node
    concurrency: 10
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
